---

driver:
  name: docker

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  requirements_path: kitchen-requirements.yml
  require_chef_for_busser: false
  require_ruby_for_busser: true

verifier:
  ruby_bindir: /usr/bin

platforms:
  - name: centos-6.7
  - name: centos-7.1
    provisioner:
      ansible_yum_repo: http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
  - name: default
