---
# Download Composer installer.
- name: Download Composer installer.
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer.php
    mode: 0755

# Run Composer installer.
- name: Run Composer installer.
  command: >
    php composer-installer.php --install-dir={{ composer_install_dir }} --filename={{ composer_filename }}
  args:
    chdir: /tmp
    creates: "{{ composer_install_dir }}/{{ composer_filename }}"
