---
- name: Check if Composer is installed.
  stat:
    path: "{{ composer_install_dir }}/{{ composer_filename }}"
  register: composer_binary

- name: Check Composer version.
  shell: |
    set -o pipefail
    {{ composer_install_dir }}/{{ composer_filename }} --version --no-interaction | grep -oe '[0-9]\+\.[0-9]\+\.[0-9\+]'
  args:
    executable: /bin/bash
  register: composer_current_version
  when: composer_binary.stat.exists
  changed_when: false

- name: Get Composer checksum.
  set_fact:
    composer_checksum: "{{ item }}"
  with_url:
    - https://composer.github.io/installer.sig

- name: Download the installer and verify it's checksum.
  get_url:
    url: https://getcomposer.org/installer
    checksum: "sha384:{{ composer_checksum }}"
    dest: /tmp/composer-setup.php
    mode: 0755
  when: not composer_binary.stat.exists

- name: Run the installer.
  command: >-
    {{ composer_php_executable }} composer-setup.php
      --install-dir={{ composer_install_dir }}
      --filename={{ composer_filename }}
      {% if composer_version %} --version={{ composer_version }}{% endif %}
  args:
    chdir: /tmp
  when: not composer_binary.stat.exists

- name: Remove the installer.
  file:
    path: /tmp/composer-setup.php
    state: absent
  when: not composer_binary.stat.exists

- name: Update Composer to the selected version (if configured).
  command: >
    {{ composer_php_executable }} {{ composer_install_dir }} self-update {{ composer_version }}
  register: composer_update
  changed_when: "'Updating to version' in composer_update.stdout"
  when: composer_binary.stat.exists and composer_version and composer_current_version != composer_version

- name: Update Composer to the latest version (if configured).
  command: >
    {{ composer_php_executable }} {{ composer_install_dir }} self-update
  register: composer_update
  changed_when: "'Updating to version' in composer_update.stdout"
  when: composer_binary.stat.exists and composer_version and composer_keep_updated
