# -*- mode: ruby -*-
# vi: set ft=ruby :

source 'https://rubygems.org'

# Rake is not available on some target platforms, like CentOS 7. Ensure that
# it's being installed.
#
# See https://github.com/test-kitchen/busser-serverspec/issues/28
gem 'rake'
