---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: t2l.composer
    image: "${MOLECULE_PLATFORM}"
    capabilities:
      - SYS_ADMIN
      - NET_ADMIN
    env:
      # The /etc/default/locale file is loaded by PAM; see /etc/pam.d/login
      # for example. However, PAM is not invoked when running a command in a
      # Docker container.
      LANG: en_US.UTF-8
      LC_ALL: en_US.UTF-8
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp/ansible
    ssh_connection:
      pipelining: true
  inventory:
    group_vars:
      all:
        composer_version: ${COMPOSER_VERSION}
        php_version: ${PHP_VERSION}
