---
name: Publish to Ansible Galaxy

# yamllint disable-line rule:truthy
on:
  workflow_run:
    workflows: ["Integrate"]
    types:
      - completed

jobs:
  publish:
    if: >-
        ${{ github.event.workflow_run.conclusion == 'success' &&
        (github.ref == 'refs/heads/2.x.x' || startsWith(github.ref, 'refs/tags/')) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Publish to Ansible Galaxy
        uses: robertdebock/galaxy-action@1.1.0
        with:
          galaxy_api_key: ${{ secrets.galaxy_api_key }}
